# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  release:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-13, macos-14, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: npm install --ignore-scripts
      - run: npx @mapbox/node-pre-gyp configure
      - run: npx @mapbox/node-pre-gyp build -j max
      - run: npm test

  debug:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm install --ignore-scripts
      - run: npx @mapbox/node-pre-gyp configure --debug
      - run: npx @mapbox/node-pre-gyp build -j max
      - run: npm test

  asan:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm install --ignore-scripts
      - run: npx @mapbox/node-pre-gyp configure --debug --enable_asan
      - run: npx @mapbox/node-pre-gyp build -j max
      - run: npm test
        env:
          MOCHA_REPEAT: 10
          LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libasan.so.6
          LSAN_OPTIONS: suppressions=${{ github.workspace }}/test/napi-leaks-suppression.txt

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm install --ignore-scripts
      - run: npx @mapbox/node-pre-gyp configure --debug --enable_coverage
      - run: npx @mapbox/node-pre-gyp build -j max
      - name: Run unit tests
        run: npx c8 npm test
      - name: Collect code coverage
        run: |
          npm run gcov
          npm run lcov
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
